# This file was generated by GoReleaser. DO NOT EDIT.
cask "cg" do
  version "1.18.0"

  on_macos do
    on_arm do
      sha256 "f723295bc18edd88f8f8a7aafed384af5fd3bea127c074247cde5f017b65094b"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d6834f9b315880e8ff39cdba5d08581d303816d154d2258821edd57e9098e7aa"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "01c4937a4d7f867f5aaffa6d3969880b986b25cd58b546eef43f657640326c66"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d8c8c0e19fb0c5b0bb1a59d923410bf80d986224e354b115cc64b7b104203a27"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cg"
  desc "Your trusted advisor for managing knowledge, projects, and ideas — powered by AI."
  homepage "https://github.com/mnemcik/consigliere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cg"]
    end
  end

  # No zap stanza required
end
