# This file was generated by GoReleaser. DO NOT EDIT.
cask "cg" do
  version "1.22.0"

  on_macos do
    on_arm do
      sha256 "34bbd23c40e1a46e37eb9f08c467df7af8288228c743de9e480313c887faab5a"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "88ca7c12ccd00137f11126308e269a3ad2840924ccdbf9d7b591591bfeb9e435"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8b9f5dcd53b6c225d075d4ec5e1ad5fb737020aa939f720cc505e29717297902"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c79f9d19d31400946584ce4a9c0f6114f0688c80faebe0a40b823b3b0753035"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cg"
  desc "Your trusted advisor for managing knowledge, projects, and ideas — powered by AI."
  homepage "https://github.com/mnemcik/consigliere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cg"]
    end
  end

  # No zap stanza required
end
