# This file was generated by GoReleaser. DO NOT EDIT.
cask "cg" do
  version "1.16.1"

  on_macos do
    on_arm do
      sha256 "233d7efbee1ed89b2f3c7e8ccc154671a35e070195745ee92725f10cd83e7a99"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07a60013335002c4137af7fc5780c7182802550c1c628eeadca5d979edbd58e4"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9bc05af75b24a7d0e411d12e1a7506af6531b250632e6a7084321a664776a577"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2355c45b5266ad8be45d4469d500043be360c6ed1c1fd7e86e755c2509d3cc5"
      url "https://github.com/mnemcik/consigliere/releases/download/v#{version}/consigliere_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cg"
  desc "Your trusted advisor for managing knowledge, projects, and ideas — powered by AI."
  homepage "https://github.com/mnemcik/consigliere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cg"]
    end
  end

  # No zap stanza required
end
